default: &default
  adapter:  mysql2
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host:     <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'root' } %>
  encoding: utf8mb4
  collation: utf8mb4_bin
  timeout:  5000

development:
  <<: *default
  database: ghb_repo_search_dev

test:
  <<: *default
  database: ghb_repo_search_test

production:
  <<: *default
  url: <%= ENV['CLEARDB_DATABASE_URL'] %>
